Gormv2: #针对 gorm 操作数据库
  UseDbType: 'mysql'
  Mysql:
    IsInitGolobalGormMysql: 1 # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30 # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
    Write:
      Host: 'mysql'
      DataBase: 'qicloud_private'
      Port: 3306
      Prefix: 'skysys_'
      User: 'root'
      Pass: 'mysql_3306'
      Charset: 'utf8mb4'
      SetMaxIdleConns: 100
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60 # 连接不活动时的最大生存时间(秒)
      #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
      #PingFailRetryTimes: 3   # 保留项,最大重连次数
    IsOpenReadDb: 0 # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read 部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: 'mysql'
      DataBase: 'qicloud_private'
      Port: 3308 #注意，非3306，请自行调整
      Prefix: 'tb_'
      User: 'root'
      Pass: 'mysql_3306'
      Charset: 'utf8'
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
  DM:
    IsInitGolobalGormMysql: 1
    Write:
      Host: "dm"
      DataBase: "qicloud_private"
      Port: 5236
      Prefix: "skysys_"
      User: "SYSDBA"
      Pass: "SYSDBA001"
      Charset: "utf8mb4"